### 게시물 목록
# @name list
GET http://localhost:3000/api/posts

### 2번 게시물 하나
GET http://localhost:3000/api/posts/{{list[1].id}}

### 없는 게시물
GET http://localhost:3000/api/posts/99

### 없는 주소
GET http://localhost:3000/api/comments

### 게시물 올리기
# @name created
POST http://localhost:3000/api/posts
Content-Type: application/json

{
  "username": "pikachu",
  "profileImage": "https://picsum.photos/seed/yuna/40/40",
  "postImage": "https://picsum.photos/seed/post4/600/600",
  "postAlt": "창밖으로 본 저녁 하늘 사진",
  "content": "오늘의 한 장 📷"
}

### 게시물 올리기 (빈 페이로드)
POST http://localhost:3000/api/posts
Content-Type: application/json

{

}

### 하트 수 고치기
PATCH http://localhost:3000/api/posts/{{created.id}}
Content-Type: application/json

{
  "likeCount": 880
}

### 게시물 지우기
DELETE http://localhost:3000/api/posts/{{created.id}}
